### ISSUE TITLE
Enable automatic downloading of raw data from URLs

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#108]
- Not clear exactly how to do that
- Might just have to allow people to add a script for that, if they want. 
  - But what would the advantage of that be, over simply adding that script to be run when the project is built?

### Proposal 1

`_projr.yml` settings (for cache and data_raw):

```yaml
script: # path to a script to run (I suppose it can be R or bash)
url: `<url_1>` # link to a bundle containing data to unzip  
```

Can always then add more specific options for specific places you can download stuff from (e.g. a `drive` section where you specify what to download from a specific Google shared drive). 

Addition to proposal 1:
```yaml
bundle:
  - url_1: <url>
  - dir_sub_1: <url>
  - url_2: <url_2>
  - dir_sub_2: <dir_sub_2>
```

Then you can specify sub-folders to save to (if desired) as well as multiple URLs.
