### ISSUE TITLE
Consider git settings in _proj.yml;

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#109]
### First proposal

```yaml
git:
  commit: true # whether to do anything
  prompt_for_message: pre # when to prompt
  changed_files: stop # or stash or ask or commit # whether to stop build if uncommitted files exist, or just ask
  commit_post_build: true # whether to commit post-build (if there are changes) 
  commit_prefix: "Bump to " # prefix before commit message
  commit_squash: false # whether to squash up until first commit or last commit prefix (risky if the commit prefix has changed!; should probably squash this)
  push: true # whether to run `git push` afterwards or not
  release: false # whether to create a versioned GitHub release using contents of `dir_output`
```

Must make it so that when you build a dev package, then we do not run git (by default).
