### ISSUE TITLE
Sort out archiving

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#276]
Okay, so under the default setting, anything that was placed in `output`, we archived.

Now, we can save something to an output folder but *not* archive it. Okay, I don't think that should be allowed, actually. That's confusing!

So, what can happen is that you can *directly* archive items without saving them to output by specifying the `archive` key but not the `output` key:
```yml
- data_raw
  - path: _data_raw
  - archive: TRUE
- output:
  - path: _output
- archive:
  - path: _archive
```

You can also not archive output:
```yml
- data_raw
  - path: _data_raw
  - output: TRUE
- output:
  - path: _output
  - archive: FALSE
- archive:
  - path: _archive
```

By default, no non-output folder is archived and all output folders are archived to every directory beginning `archive`.
