### ISSUE TITLE
Make package builds a content label, rather than an individual _projr.yml item

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#456]
Instead of 

```yaml
build:
  dev-output: yes
  package: yes
  github:
    "@version":
      content: code
      body: "Latest source code"
```

have

```yaml
build:
  dev-output: yes
  git: yes
  github:
    "@version":
      content: [code, package]
      body: "Latest source code"
```

This will also mean that you don't specify the package location in the `directories` key.
