### ISSUE TITLE
Enable using 

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#485]
This build setting:

```yml
build:
  github:   
    '@version':
       content: code
       description: Latest source code
       send:
         version-source: file
``` 

triggers this error message:

```r
Error: path_dir must be a non-empty string
```

which happens because this code

```r
.projr_change_get_dir(path_dir_pre = path_dir_local_pre, path_dir_post = path_dir_local_post)
```

returns `FALSE`. 

When running 

```r
path_dir_local_pre <- .projr_change_get_file_dir(type = type_pre, 
    remote = remote_pre)
```

these are the values of `type_pre` and `remote_pre`

![image](https://github.com/SATVILab/projr/assets/23501332/31f5ef34-a732-4956-a2a1-d6af4c545835)

which looks wrong.
