### ISSUE TITLE
Update default `_projr.yml` file and add `_projr-archive.yml`

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#486]
Default `_projr.yml`:

```yml
directories:
  data-raw:
    path: _data_raw
  cache:
    path: _tmp
  output:
    path: _output
  docs:
    path: docs
build:
  github:
    input:
      content: data-raw
      structure: latest
    output:
      content:
      - output
      - docs
      structure: latest
```

Default `_projr-archive.yml`:

```yml
build:
  github:
    archive:
      content:
      - data-raw
      - docs
      - output
      structure: version
      send:
        sync-approach: sync-using-deletion
        version-source: none
```
