### ISSUE TITLE
Fix upload-all to GitHub remotes not retaining old files

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#497]
The plan is automatically `delete_add_all` with these settings:

```yaml
build:
  github:
    docs-2024:
      content: docs
      send:
        sync-approach: upload-all
```

However, we need to actually download whatever's there, and "merge" the two files, with the local objects overwriting the stuff from GitHub.
