### ISSUE TITLE
Identify standard components to `_output.yml`

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#5]
Probably a good idea to use the `bookdown` defaults, but replace the references to `bookdown` with references to the project or its GitHub repository:

```yml
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    edit: https://github.com/USERNAME/REPO/edit/BRANCH/%s
    download: ["pdf", "epub"]
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
bookdown::epub_book: default
```

For example, the above would become
```yml
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">DataTidy22BCGCorrPilot</a></li>
      after: |
        <li><a href="https://github.com/SATVILab/DataTidy22BCGCorrPilot" target="blank">DataTidy22BCGCorrPilot</a></li>
    edit: https://github.com/SATVILab/DataTidy22BCGCorrPilot/edit/BRANCH/%s
    download: ["pdf", "epub"]
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
bookdown::epub_book: default

```
