### ISSUE TITLE
Fix the GitHub `parse_url` bug

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#505]
![image](https://github.com/SATVILab/projr/assets/23501332/0bf8c696-d10c-4f54-95fb-60155bf5b182)

This is the structure of `_projr-archive.yml` (with `archive` profile activated during build):

```yaml
build:
  github:
    archive-2024:
      content:
      - data-raw-img
      - data-raw-slides
      - docs
      - output
      structure: version
      send:
        sync-approach: sync-using-deletion
        version-source: none
```

and this is the structure of `_projr.yml`:

```yaml
directories:
  data-raw-img:
    path: _data_raw/img
  data-raw-slides:
    path: _data_raw/slides
  cache:
    path: _tmp
  output:
    path: _output
  docs:
    path: docs
build:
  github:
    latest-2024:
      content:
      - data-raw-img
      - data-raw-slides
      - docs
      - output
      structure: latest
      send:
        version-source: none
        sync-approach: upload-all
```

Despite the errors, this was the release structure post build:

![image](https://github.com/SATVILab/projr/assets/23501332/3c3f33bf-d816-44e6-a8b9-2b025d240ef5)
