### ISSUE TITLE
Stop `projr` creating `NA: ~` keys

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#542]
It creates alarming errors, and possibly stops functionality

```yml
directories:
  data-raw:
    path: _data_raw
  cache:
    path: _tmp
  output:
    path: _output
  docs:
    path: docs
NA: ~
build:
  git: yes
  github:
    input:
      content: data-raw
    output:
      content:
      - output
      - docs
```
