### ISSUE TITLE
Allow explicitly specifying docs to build in `_projr.yml`

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#554]
At present, we rely on automatic detection or on `_bookdown.yml`/`_quarto.yml`.
However, this means (for most projects) building every file every time. This can be cumbersome. 

So, whilst it is something of a break from the "overall, linear project version" philosophy (as now the project version can be bumped while only adding a part of it), this seems like something we would want to do. If people are careful with their `output` keys (e.g. use `output-data` when just running the data scripts), this should be fine. However, this is something of a problem with the `docs` key, as we assume there is only one... 

Okay, so the proposal for now is that it gets specified under the `build.scripts` key, either at that level or under a `build` sub-key, like so:

```yml
build:
  scripts:
    - script1.qmd
    - script2.qmd
    pre: script3.R
    post: script4.R
```

OR (also to be supported):

```yml
build:
  scripts:
    build:
    - script1.qmd
    - script2.qmd
    pre: script3.R
    post: script4.R
```

The reason for putting these under the `scripts` key is that a) we want to support scripts, actually (like just give an `R` file), and b) we do want pre- and post-build scripts, and don't want to add another key directly under `build`. 

The motivation for the pre-build script is, in part, that it can be used to download raw data that then gets versioned (we version raw data before running any build scripts). The post-build script is, similarly, for sending around and organising outputs and docs after they've been put into their final places. These are also only run when it's a non-development build (that is, the pre- and post-build scripts), so they're really quite different.
